[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
langchain = "*"
langchain-community = "^0.2.5"
spacy = "^3.7.5"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
